# Generated by Django 5.2.5 on 2025-08-16 06:17

import django.core.validators
import django.db.models.deletion
import kyc.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_file_size_mb", models.PositiveIntegerField(default=5)),
                (
                    "allowed_file_types",
                    models.JSONField(
                        default=list,
                        help_text="List of allowed file extensions, e.g., ['jpg', 'png', 'pdf']",
                    ),
                ),
                (
                    "required_documents_basic",
                    models.JSONField(
                        default=list,
                        help_text="Required document types for basic verification",
                    ),
                ),
                (
                    "required_documents_enhanced",
                    models.JSONField(
                        default=list,
                        help_text="Required document types for enhanced verification",
                    ),
                ),
                (
                    "required_documents_premium",
                    models.JSONField(
                        default=list,
                        help_text="Required document types for premium verification",
                    ),
                ),
                ("enable_auto_approval", models.BooleanField(default=False)),
                (
                    "auto_approval_threshold",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Confidence score threshold for auto-approval (0-100)",
                    ),
                ),
                ("notify_on_submission", models.BooleanField(default=True)),
                ("notify_on_approval", models.BooleanField(default=True)),
                ("notify_on_rejection", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KYC Configuration",
                "verbose_name_plural": "KYC Configurations",
            },
        ),
        migrations.CreateModel(
            name="KYCProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(max_length=100)),
                (
                    "id_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="SA ID number must be 13 digits",
                                regex="^\\d{13}$",
                            )
                        ],
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("SA_ID", "South African ID"),
                            ("PASSPORT", "Passport"),
                            ("DRIVERS_LICENSE", "Driver's License"),
                        ],
                        default="SA_ID",
                        max_length=50,
                    ),
                ),
                ("street_address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                ("country", models.CharField(default="South Africa", max_length=100)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("EMPLOYED", "Employed"),
                            ("SELF_EMPLOYED", "Self Employed"),
                            ("UNEMPLOYED", "Unemployed"),
                            ("STUDENT", "Student"),
                            ("RETIRED", "Retired"),
                        ],
                        max_length=50,
                    ),
                ),
                ("employer_name", models.CharField(blank=True, max_length=200)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REQUIRES_UPDATE", "Requires Update"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "verification_level",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic Verification"),
                            ("ENHANCED", "Enhanced Verification"),
                            ("PREMIUM", "Premium Verification"),
                        ],
                        default="BASIC",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyc_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID_FRONT", "ID Document Front"),
                            ("ID_BACK", "ID Document Back"),
                            ("PASSPORT", "Passport"),
                            ("PROOF_OF_ADDRESS", "Proof of Address"),
                            ("BANK_STATEMENT", "Bank Statement"),
                            ("SELFIE", "Selfie with ID"),
                            ("EMPLOYMENT_LETTER", "Employment Letter"),
                            ("PAYSLIP", "Payslip"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(upload_to=kyc.models.kyc_document_path),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kyc_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="kyc.kycprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "unique_together": {("kyc_profile", "document_type")},
            },
        ),
        migrations.CreateModel(
            name="KYCVerificationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("UPDATE_REQUESTED", "Update Requested"),
                            ("DOCUMENT_UPLOADED", "Document Uploaded"),
                            ("DOCUMENT_APPROVED", "Document Approved"),
                            ("DOCUMENT_REJECTED", "Document Rejected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kyc.kycdocument",
                    ),
                ),
                (
                    "kyc_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="kyc.kycprofile",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
